import { chromium } from 'playwright';
const [url, out, y, cx, cy, cw, ch] = process.argv.slice(2);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
await p.goto(url, { waitUntil: 'networkidle', timeout: 60000 }).catch(()=>{});
await p.waitForTimeout(4000);
await p.evaluate((yy)=>window.scrollTo(0,yy), Number(y));
await p.waitForTimeout(2000);
await p.screenshot({ path: out, clip: { x: Number(cx), y: Number(cy), width: Number(cw), height: Number(ch) } });
console.log('ok '+out);
await b.close();
